apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: harbor-cred
      containers:
        - name: app
          image: 3.38.46.241/test/test:jenkins-test-126
          ports:
            - containerPort: 80
