apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  revisionHistoryLimit: 1
  replicas: 2
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: harbor-cred
      containers:
        - name: app
          image: 3.38.46.241/test/test:jenkins-test-159
          ports:
            - containerPort: 80
