apiVersion: v1
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICIzLjExMC45LjM0IjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJZV1J0YVc0NlNHRnlZbTl5TVRJek5EVT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
kind: Secret
metadata:
  name: harbor-cred
  namespace: study
type: kubernetes.io/dockerconfigjson
